/* Justin Robb
 * 3-27-14
 * JetPack
 * Useful Enums
*/

#ifndef ENUMS_H_
#define ENUMS_H_

#include "AbstractThing.h"
const float PI = 3.14159265359f;

int m_rand();
void init_rand();
float m_randf();
AbstractThing* getThingFromCode(int code, float x, float y, float width, float height, Sprites *sprites);

enum GeneralTypeEnum { BADDIE,
					   SOLID,
					   NONSOLID,
					   COLLECTABLE,
					   OTHER };

/* Sprite identifiers, corrosponding to the sprites loaded using the same order as SpriteNames[] */
enum SpriteEnum {   SPRITE_GAMEOVER_WEB_FINAL,
					SPRITE_IVY,
					SPRITE_PILLAR,
					SPRITE_REDSWITCH,
					SPRITE_BACKGROUND,
					SPRITE_BAT1,
					SPRITE_BAT2,
					SPRITE_BAT3,
					SPRITE_BAT4,
					SPRITE_BLOWINGUP,
					SPRITE_BLOWINGUP2,
					SPRITE_BLOWINGUP3,
					SPRITE_BLOWINGUP4,
					SPRITE_BLOWINGUP5,
					SPRITE_BLOWINGUP6,
					SPRITE_BLUESWITCH,
					SPRITE_BLUESWITCHSOLID,
					SPRITE_BOX,
					SPRITE_CONVEYORSOLID1,
					SPRITE_CONVEYORSOLID2,
					SPRITE_CONVEYORSOLID3,
					SPRITE_CONVEYORSOLID4,
					SPRITE_CONVEYORSOLID5,
					SPRITE_CREDITS,
					SPRITE_D,
					SPRITE_DEAD,
					SPRITE_DEATHDOWN,
					SPRITE_DEATHLEFT,
					SPRITE_DEATHRIGHT,
					SPRITE_DEATHUP,
					SPRITE_DOORCLOSED,
					SPRITE_DOORCLOSING2,
					SPRITE_DOOROPEN,
					SPRITE_DOOROPENING1,
					SPRITE_DYING1,
					SPRITE_DYING2,
					SPRITE_DYING3,
					SPRITE_DYING4,
					SPRITE_DYING5,
					SPRITE_EGG,
					SPRITE_FASTSOLID,
					SPRITE_FRONT,
					SPRITE_FUEL,
					SPRITE_FUELBACK,
					SPRITE_FUELRED,
					SPRITE_FUELYELLOW,
					SPRITE_FULLFUEL,
					SPRITE_GEM,
					SPRITE_GEMCOLLECTED,
					SPRITE_GOLD1,
					SPRITE_GOLD2,
					SPRITE_GOLD3,
					SPRITE_GOLD4,
					SPRITE_GOLDSWITCH,
					SPRITE_GOLDSWITCHSOLID,
					SPRITE_GREENTELEPORTER,
					SPRITE_HALFFUEL,
					SPRITE_HARDERSOLID,
					SPRITE_HBLUESWITCHSOLID,
					SPRITE_HEROTELEPORTINGGREEN1,
					SPRITE_HEROTELEPORTINGGREEN2,
					SPRITE_HEROTELEPORTINGPURPLE1,
					SPRITE_HEROTELEPORTINGPURPLE2,
					SPRITE_HEROTELEPORTINGYELLOW1,
					SPRITE_HEROTELEPORTINGYELLOW2,
					SPRITE_HGOLDSWITCHSOLID,
					SPRITE_HREDSWITCHSOLID,
					SPRITE_HUNTERH1,
					SPRITE_HUNTERH2,
					SPRITE_HUNTERV1,
					SPRITE_HUNTERV2,
					SPRITE_ICESOLID,
					SPRITE_INVINCIBILITY,
					SPRITE_INVINCIBILITY1,
					SPRITE_JETPACK_0,
					SPRITE_JUMPING,
					SPRITE_L,
					SPRITE_LADDER,
					SPRITE_LADDER2,
					SPRITE_LADDER3,
					SPRITE_LADDER4,
					SPRITE_LEFT1,
					SPRITE_LEFT2,
					SPRITE_LEFTJET,
					SPRITE_LOADSAVE,
					SPRITE_LOWERBACKGROUND,
					SPRITE_MINE,
					SPRITE_MISSILEDOWN1,
					SPRITE_MISSILEDOWN2,
					SPRITE_MISSILELEFT1,
					SPRITE_MISSILELEFT2,
					SPRITE_MISSILERIGHT1,
					SPRITE_MISSILERIGHT2,
					SPRITE_MISSILEUP1,
					SPRITE_MISSILEUP2,
					SPRITE_MOSSSOLID,
					SPRITE_NONPSOLID,
					SPRITE_PHASEDOWN1,
					SPRITE_PHASEDOWN2,
					SPRITE_PHASINGLEFT1,
					SPRITE_PHASINGLEFT2,
					SPRITE_PHASINGRIGHT1,
					SPRITE_PHASINGRIGHT2,
					SPRITE_PHASINGUP1,
					SPRITE_PHASINGUP2,
					SPRITE_PINWHEEL1,
					SPRITE_PINWHEEL2,
					SPRITE_PINWHEEL3,
					SPRITE_PINWHEEL4,
					SPRITE_PURPLETELEPORTER,
					SPRITE_R,
					SPRITE_REDSWITCHSOLID,
					SPRITE_RIGHT1,
					SPRITE_RIGHT2,
					SPRITE_RIGHTJET,
					SPRITE_ROBOLEFT1,
					SPRITE_ROBOLEFT2,
					SPRITE_ROBORIGHT1,
					SPRITE_ROBORIGHT2,
					SPRITE_SOLID,
					SPRITE_SOLIDPHASED,
					SPRITE_SOLIDPHASING1,
					SPRITE_SOLIDPHASING2,
					SPRITE_SPRING1,
					SPRITE_SPRING2,
					SPRITE_SPRINGSMALL,
					SPRITE_TIMER,
					SPRITE_TIMER2,
					SPRITE_U,
					SPRITE_WIN,
					SPRITE_WIN1,
					SPRITE_WIN2,
					SPRITE_WIN3,
					SPRITE_YELLOWTELEPORTER,
					SPRITE_COUNT};

/* special attributes of solid blocks */
enum SolidAttributesEnum {  ICY,
							MOSSY,
							SHIELDED_LEFT,
							SHIELDED_RIGHT,
							SHIELDED_UP,
							SHIELDED_DOWN,
							CONVEYOR_RIGHT,
							CONVEYOR_LEFT,
							ATTRIBUTE_COUNT };

/* differentate between directions */
enum DirectionEnum {  UP, DOWN, LEFT, RIGHT};


/* Difffent switch groups */
enum SwitchGroupEnum {  SWITCH_RED_V, 
						SWITCH_BLUE_V, 
						SWITCH_GOLD_V,
						SWITCH_RED_H, 
						SWITCH_BLUE_H, 
						SWITCH_GOLD_H,
						SWITCH_COUNT };

/* Difffent teleporter groups */
enum TeleporterGroupEnum {  TELE_PURPLE,
						TELE_GREEN, 
						TELE_YELLOW,
						TELE_COUNT };


/* Identifiers for the edit level menu, as well as general types of things */
enum TypeEnum {		TYPE_DOOR,
					TYPE_HERO,
					TYPE_GEM,
					
					// Baddies
					TYPE_ROBOT,
					TYPE_SPRING,
					TYPE_PINWHEEL,
					TYPE_EGG,
					TYPE_MISSILE,
					TYPE_BAT,
					TYPE_HUNTER,
					TYPE_MINE,
					TYPE_DEATHDOWN,
					TYPE_DEATHLEFT,
					TYPE_DEATHRIGHT,
					TYPE_DEATHUP,

					// switches
					TYPE_GOLDSWITCH,
					TYPE_BLUESWITCH,
					TYPE_REDSWITCH,

					// switch solids
					TYPE_HBLUESWITCHSOLID,
					TYPE_BLUESWITCHSOLID,
					TYPE_HREDSWITCHSOLID,
					TYPE_REDSWITCHSOLID,
					TYPE_HGOLDSWITCHSOLID,
					TYPE_GOLDSWITCHSOLID,

					// solid things
					TYPE_BRICKSOLID,
					TYPE_BRICKSOLID_ICY,
					TYPE_BRICKSOLID_MOSSY,
					TYPE_BRICKSOLID_CONVEYOR_L,
					TYPE_BRICKSOLID_CONVEYOR_R,
					TYPE_SHIELDED_BRICK_D,
					TYPE_SHIELDED_BRICK_U,
					TYPE_SHIELDED_BRICK_L,
					TYPE_SHIELDED_BRICK_R,
					TYPE_WOODSOLID,
					TYPE_WOODSOLID_ICY,
					TYPE_WOODSOLID_MOSSY,
					TYPE_WOODSOLID_CONVEYOR_L,
					TYPE_WOODSOLID_CONVEYOR_R,
					TYPE_SHIELDED_WOOD_D,
					TYPE_SHIELDED_WOOD_U,
					TYPE_SHIELDED_WOOD_L,
					TYPE_SHIELDED_WOOD_R,
					TYPE_STONESOLID,
					TYPE_STONESOLID_ICY,
					TYPE_STONESOLID_MOSSY,
					TYPE_STONESOLID_CONVEYOR_L,
					TYPE_STONESOLID_CONVEYOR_R,
					TYPE_BOX,
					TYPE_FASTSOLID,

					// Items
					TYPE_TIMER,
					TYPE_FULLFUEL,
					TYPE_HALFFUEL,
					TYPE_INVINCIBILITY,

					// Gold
					TYPE_GOLD1,
					TYPE_GOLD2,
					TYPE_GOLD3,
					TYPE_GOLD4,

					// ladders
					TYPE_LADDER,
					TYPE_LADDERUP,
					TYPE_LADDERDOWN,

					// teleporters
					TYPE_GREENTELEPORTER,
					TYPE_PURPLETELEPORTER,
					TYPE_YELLOWTELEPORTER,

					// misc things
					TYPE_PILLAR,
					TYPE_IVY,
					TYPE_COUNT };

/* Holds the filenames for all the sprites, order is important */
extern const char *SpriteNames[];

#endif // ENUMS_H_